### ISSUE TITLE
Will not authorize despite logging in successfully

### ISSUE THREAD

**Issue by Tp-danny** [Lacro59/playnite-howlongtobeat-plugin#162] opened 2022-09-14 15:45 UTC
The addon asks for authorization, but yet when logging in successfully in the window, the window does not autoclose and the addon does not recognize the sign in. Closing the window manually does not resolve this either.

**Comment by KShivum** [comment] 2022-09-14 23:01
Same here as well.

**Comment by Jeshibu** [comment] 2022-09-15 16:47
#161 and this have the same root cause: their website updated and now nothing is where the plugin expects it to be

**Comment by sukarn-m** [comment] 2022-09-16 13:13
Interesting discussion related to search and getting times (but not authorization and sending your own times):

https://github.com/ckatzorke/howlongtobeat/issues/40

**Comment by barrelltitor** [comment] 2022-09-16 19:11
I'm also having this issue, just set up everything on a fresh install of playnite so it is most likely related to their changes

**Comment by sukarn-m** [comment] 2022-09-16 19:53
It's affecting everyone. As mentioned by @Jeshibu, the website has changed URL formats, what data is to be submitted, what data is returned, the format in which all of that happens, etc. A significant part of the source code might need to be changed. Until the plugin is updated, everyone will remain affected.

If you want, you can show your support by giving a thumbs up to the first comment or any potential solutions that are discussed here. Let's please try to keep the discussion focused on any fixes, or any information that could help develop fixes.

**Comment by SquishyMochi514** [comment] 2022-09-22 07:48
Already fixed that one, but I would like to do a PR with all the API updates as well  : 
![image](https://user-images.githubusercontent.com/42750224/191688540-adc3f6c7-3072-440d-a05a-afe7052969eb.png)

**Comment by Lacro59** [comment] 2022-09-30 10:51
@SquishyMochi514 I started updating this based on the work of @Jhanlon95.
Can you base yourself on this and merge with your work in order to finalize your future pull request?

**Comment by SquishyMochi514** [comment] 2022-09-30 12:46
Will do. I m working on the POCO request and logic to push data but it changes a lot the code base. I tried to keep the same logic updating the time but as pushing change I kinda have to re-eng how it was done before to apply the same logic.

**Comment by SquishyMochi514** [comment] 2022-09-30 12:50
There is also a minor bug that now a search for user game list not authenticated will return all the available data from the website instead of nothing. We defaulted the page size to 1000 games so it really slowed everything down for nothing 🤣. Edge case to address :)

**Comment by infekSK** [comment] 2022-10-10 00:07
So this was updated with the latest Playnite release but it still doesn't keep you authenticated nor does it upload any data.

**Comment by Lacro59** [comment] 2022-10-12 09:47
fixed with last release

**Closed by Lacro59** 2022-10-12 09:47 UTC
